language: node_js
node_js:
- '7'

deploy:
  provider: npm
  email: jingkai.zhao@foxmail.com
  api_key:
    secure: bONbRuWxdnIIIMzQEO+2XI/gpGjX5JQjQJwQ691IAIqc6JrFIB9MaTntAV/K1R1HGiaIdy2QjRhoXvVS7BRj4RU10Zh4T4BaC5EsBGcTCr1JCPUp7nw04HKFMFPGGGeTu7ScyDCV/VFvTnMB86ML3cT2auMaIh1OSoso3uoCmTgqi0/MkS+L3l96aOS/flIEeG+brh/gKozMDcx4BycrmES3zrRESTmu0jKxZtz57i95EgMr+Glf/QOexhlYmbjmj1gsZMenLH7pmOoXCXUrXr1GY6g/PptWkBLdaLVgZnJI0T4I5rb+4QkOXyUOIVJIvkFt5boQj7GJoALTzRhs1kgUC9uTL8gtms+7B9Sth8YMRQ68UNwwh1C0MliUzSsu6i7LideQWfhQXDxsjGIBIC2AnMKcY77xszlCDCVLTp3pSA94mj6dIoM5Eemz5IABqvDvgXGK7HGwFrHxiGJGkasVtscwtNsRvPDEQnVB8iJOvRcqO38VFzNVc6iKHNVAHYSAWGAS3AOv502vPF1fTWpQIWKzpUXx6UWs6C3UVaPzaFV0tOPKB5gNetTA6Q3TcGdspl7/edgtvzCfuLo9kjFx2YZS3gRV5ZY+WNdow3jmLWZ04sdnWZQAhRGO+8pZljtUiYFhPgU2BTZghlm6rospI5Fx7mtGqNshjo66HHI=
  on:
    tags: true
    repo: hui-z/corgi-cli
